projects = { "/Users/y-kubo/.dotfiles" = { trust_level = "trusted" } , "/Users/y-kubo/Developments/zero/boba-admin" = { trust_level = "trusted" } , "/Users/y-kubo/Developments/zero/boba-server" = { trust_level = "trusted" } , "/Users/y-kubo/Developments/zero/boba-app" = { trust_level = "trusted" } }
notify = ["bash", ".codex/notify_macos.sh"]
model = "gpt-5-codex"

# 推論の深さ（none | low | medium | high）
model_reasoning_effort = "high"

# 推論サマリーの表示（auto | none）
model_reasoning_summary = "auto"

# 推論ログの見た目を抑える（表示制御）
hide_agent_reasoning = true
show_raw_agent_reasoning = false
network_access = true

[tools]
web_search = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.figma]
command = "npx"
args = ["-y", "mcp-remote", "http://127.0.0.1:3845/sse"]

