typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/iqfjk6b33yyv7rqqhf7h9r9icihg32yn-zsh-5.9/share/zsh/$ZSH_VERSION/help"

# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git docker brew github zsh-autosuggestions zsh-syntax-highlighting zsh-completions)
ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"
ZSH_THEME="agnoster"
source $ZSH/oh-my-zsh.sh

eval "$(/nix/store/p2dkbz6qk282byzp7mp3grkb602gk9b6-zoxide-0.9.8/bin/zoxide init zsh )"

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="/Users/y-kubo/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK

# Enabled history options
enabled_opts=(
  HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY
)
for opt in "${enabled_opts[@]}"; do
  setopt "$opt"
done
unset opt enabled_opts

# Disabled history options
disabled_opts=(
  APPEND_HISTORY EXTENDED_HISTORY HIST_EXPIRE_DUPS_FIRST HIST_FIND_NO_DUPS
  HIST_IGNORE_ALL_DUPS HIST_SAVE_NO_DUPS
)
for opt in "${disabled_opts[@]}"; do
  unsetopt "$opt"
done
unset opt disabled_opts

if [[ $options[zle] = on ]]; then
  source <(/nix/store/2qzpswmq7v8zdq12cbh65r156c77fr1h-fzf-0.67.0/bin/fzf --zsh)
fi

eval "$(/nix/store/lw9kh2ydbmck4h7j2qcc0d8163ndjsyl-mise-2026.1.2/bin/mise activate zsh)"

eval "$(/nix/store/91q05bqw755yg3whqg1vhqi1v6glaxl3-direnv-2.37.1/bin/direnv hook zsh)"

# ZSH Syntax Highlighting configuration
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets cursor root)

# 連想配列
typeset -A ZSH_HIGHLIGHT_STYLES
# ブラケット
# マッチしない括弧
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=red,bold'
# 括弧の階層
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=blue,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=magenta,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg=yellow,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-5]='fg=cyan,bold'
# カーソルがある場所にマッチする括弧
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='standout'
# カーソル
ZSH_HIGHLIGHT_STYLES[cursor]='bg=blue'
# ルートユーザーの色を変える
ZSH_HIGHLIGHT_STYLES[root]='bg=red'

# zsh-autosuggestions color configuration
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=244'

# Google Cloud SDK
GCP_SDK_PATH="${GCP_SDK_PATH:-/opt/homebrew/share/google-cloud-sdk}"
if [ -f "$GCP_SDK_PATH/path.zsh.inc" ]; then . "$GCP_SDK_PATH/path.zsh.inc"; fi
if [ -f "$GCP_SDK_PATH/completion.zsh.inc" ]; then . "$GCP_SDK_PATH/completion.zsh.inc"; fi
export PATH="$GCP_SDK_PATH/bin:$PATH"

# Uv environment
if [ -f "$HOME/.local/bin/env" ]; then . "$HOME/.local/bin/env"; fi

# ファイルの内容をクリップボードにコピーする関数
ccopy() {
  if [ -f "$1" ]; then
    cat "$1" | pbcopy
    echo "'$1' の内容をクリップボードにコピーしました。"
  else
    echo "エラー: ファイル '$1' が見つからないか、有効なファイルではありません。"
  fi
}

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Go environment
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"

# Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"

alias -- c=claude
alias -- cat=bat
alias -- dc='docker compose'
alias -- g=git
alias -- gd='git diff'
alias -- gl='git log --oneline'
alias -- gp='git push'
alias -- grsh='git reset --soft HEAD^'
alias -- gs='git status'
alias -- la='eza -a'
alias -- ll='eza -la'
alias -- ls=eza
alias -- lt='eza --tree'
alias -- nix-rebuild='darwin-rebuild switch --flake ~/.dotfiles/nix#darwin --impure'
alias -- nix-update='cd ~/.dotfiles/nix && nix run .#update --impure'
alias -- v='nvim .'